services:
  admin:
    container_name: kasaba-admin
    depends_on:
      - server
    build:
      context: admin
      args:
        - NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
    networks:
      - kasaba-net
  client:
    container_name: kasaba-client
    depends_on:
      - server
    build:
      context: client
      args:
        - NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
    networks:
      - kasaba-net
  server:
    container_name: kasaba-server
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
      redis:
        condition: service_started
    ports:
      - "4040:4040"
    environment:
      - CLIENT_URL=$CLIENT_URL
      - DATABASE_URL=$DATABASE_URL
      - SECRET_KEY=$SECRET_KEY
      - PORT=$SERVER_PORT
      - MINIO_ENDPOINT_API=$MINIO_ENDPOINT_API
      - MINIO_ENDPOINT=$MINIO_ENDPOINT
      - MINIO_ACCESS_KEY=$MINIO_ROOT_USER
      - MINIO_SECRET_KEY=$MINIO_ROOT_PASSWORD
      - MINIO_BUCKET=$MINIO_BUCKET
    build:
      context: server
    platform: linux/arm64
    networks:
      - kasaba-net
  minio:
    image: quay.io/minio/minio
    container_name: kasaba-minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
      MINIO_UPDATE: off
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - kasaba-net
  postgres:
    image: postgres:15
    container_name: kasaba-postgres
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - kasaba-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
  redis:
    image: redis:7
    container_name: kasaba-redis
    restart: always
    networks:
      - kasaba-net

volumes:
  pgdata:
  minio-data:

networks:
  kasaba-net:
    driver: bridge
