import "./globals.css";
import "react-photo-view/dist/react-photo-view.css";

import { NuqsAdapter } from "nuqs/adapters/next/app";
import { ThemeProvider } from "next-themes";
import { cn } from "@heroui/theme";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import { useEffect } from "react";
import Script from "next/script";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Admin",
  description: "Generated by admin",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        {/* Telegram WebApp SDK */}
        <Script src="/telegram-web-app.js" strategy="beforeInteractive" />
      </Head>
      <body
        className={cn(
          "min-h-screen overflow-hidden bg-slate-100 antialiased dark:bg-slate-900",
          inter.className,
        )}
      >
        <ThemeProvider defaultTheme="light">
          <NuqsAdapter>{children}</NuqsAdapter>
        </ThemeProvider>
      </body>
    </html>
  );
}
