import "../globals.css";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "aos/dist/aos.css";

import Header from "@/components/root/layout/header";
import Navbar from "@/components/root/layout/navbar";
import Footer from "@/components/root/layout/footer";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cn } from "@/libs/utils";
import AOSProviderDynamic from "@/providers/aos-dynamic";
import { i18n, Locale } from "@/configs/i18n";
import { getDictionary } from "@/utils/directory";
import { getMenuTree } from "../../action/menu";
import { getLanguages } from "../../action/language";
import { TranslationsProvider } from "@/utils/translation-provider";
import { ModalProvider } from "@/providers/modal-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Respublika Kengashi",
  description: "Generated by ByteSynergy",
  icons: "/img/logo.svg",
};

export const revalidate = 0;

export async function generateStaticParams() {
  return i18n.locales.map((lang) => ({
    lang,
  }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: Locale }>;
}>) {
  const { lang } = await params;
  const t = await getDictionary(lang);

  // ✅ Menuni server action orqali olish
  const menuResult = await getMenuTree(lang);
  const menu = menuResult.success ? menuResult.data : [];

  // ✅ Fillanguages server action orqali olish
  const langResult = await getLanguages();
  const languages = langResult.data || [];

  return (
    <html lang={lang} suppressHydrationWarning>
      <body
        className={cn(
          "antialiased flex flex-col min-h-screen",
          geistSans.variable,
          geistMono.variable
        )}
      >
        <AOSProviderDynamic>
          <TranslationsProvider dictionary={t}>
            <ModalProvider lang={lang} menu={menu}>
              <Header header_desc={t.header.description} lang={lang} menu={menu} languages={languages} />
              <Navbar menu={menu} lang={lang} />
              <main className="py-5 max-md:p-0">{children}</main>
              <Footer lang={lang} />
            </ModalProvider>
          </TranslationsProvider>
        </AOSProviderDynamic>
      </body>
    </html>
  );
}
